apiVersion: v1
data:
  config: |
    address-pools:
    - addresses:
      - 192.168.161.204-192.168.161.214
      name: default
      protocol: layer2
    - addresses:
      - 192.168.161.215-192.168.161.224
      name: network-services
      protocol: layer2
kind: ConfigMap
metadata:
  labels:
    app: metallb
    chart: metallb-0.8.3
    heritage: Tiller
    release: metallb
  name: metallb
  namespace: metallb-system
